### ISSUE TITLE
Test Policy of Lambda access to the Aurora DB.

### ISSUE THREAD

**Issue by mattyplo** [North-Seattle-College/ad440-winter2020-thursday-repo#127]
Test task #126

**Comment by YunFSui** [comment]
# Objective
Test if newly created lambda attaches the right policy to access Aurora DB

# Test Method
## Test script to create lambda:
[create_lambda_function.py](https://github.com/North-Seattle-College/ad440-winter2020-thursday-repo/blob/feature-sprint3-kyleo83/Automation/create_lambda_function.py) is tested under command line environment using lambda function naming conform/nonconform to the new naming convention as of Sprint3 wk1. The script successfully reject nonconforming names, and create new lambdas with the conforming names. 

It will also report error when try to create a new lambda function which has the same name as an existing one.
## Verify creation in lambda console:
The lambda is created with the same name in the lambda console
## Verify the lambda is attached to the correct policy:
It is decided we use a single lambda IAM role/policy for ease of management going forward. I verified the newly created lambda is attached to the correct role.
## Verify the role has access to Aurora DB
The role has access to RDS as specified by the policy. And I verified this by attach the same policy to an existing lambda with RDS accessibility and tested its validity.

# Result
I found no error with the particular implementation of the task. One suggestion is that the function can be modified so that it has the ability take a list of names and allow bulk processing as that is more inline of what the DevOps team was doing in past sprints.
