### ISSUE TITLE
Cognito User Deletion Lack of Feedback

### ISSUE THREAD

**Issue by YunFSui** [North-Seattle-College/ad440-winter2020-thursday-repo#236]
When user is successfully deleted the script does not give any feedback that the user is deleted.

(Also, if possible, maybe added an extra step like require to type the user name again, to avoid accidental deletion)

**Comment by kyleo83** [comment]
I added a message for when the user is successfully deleted, successfully not deleted (user changes mind), an error message if an error occurs and the response for anything else.

I also added a check so that the user must enter 'y' or 'yes' to confirm delete user. If any other key is pressed the user is not deleted.

**Comment by YunFSui** [comment]
test and it work as expected, nice!
