### ISSUE TITLE
TT2: Test API Add Property

### ISSUE THREAD

**Issue by UnTamedLaw** [North-Seattle-College/ad440-winter2020-thursday-repo#24]

**Comment by anuslorah** [comment]
**Test Objective:**
behavior of POST /property
**Environment**
With CMD curl -X POST

**empty POST request**
curl -X POST https://ez9pmaodek.execute-api.us-west-2.amazonaws.com/Feature/property

Expected:
response status code 400

Received:
{"statusCode":400,"body":"{\"message\":\"Missing required data\"}"}

**POST ideal json**
C:\>curl -X POST -d @test.json https://ez9pmaodek.execute-api.us-west-2.amazonaws.com/Feature/property --header "Content-Type:application/json"

Content of test.json:
{"property_id": 5, 
"property_name": "foo property", 
"property_type": 1, 
"property_address": "111 Main St", 
"property_city": "Seattle",
"property_state": "WA",
"property_zip": 12345,
"property_country": "USA"};

Expected result:
Echo back the json in the body and status code 200

Received:
{"statusCode":200,"body":"{\"property_id\":5,\"property_name\":\"foo property\",\"property_type\":1,\"property_address\":\"111 Main St\",\"property_city\":\"Seattle\",\"property_state\":\"WA\",\"property_zip\":12345,\"property_country\":\"USA\"}"}

**POST json with wrong data type**
C:\>curl -X POST -d @test.json https://ez9pmaodek.execute-api.us-west-2.amazonaws.com/Feature/property --header "Content-Type:application/json"

Content of test.json:
{"property_id": "1", 
"property_name": "foo property", 
"property_type": 1, 
"property_address": "111 Main St", 
"property_city": "Seattle",
"property_state": "WA",
"property_zip": 12345,
"property_country": "USA"};

Expected result:
Status code 400, Error message

Received:
{"statusCode":400,"body":"{\"message\":\"Invalid datatype provided\"}"}

**POST json with missing parameter**
C:\>curl -X POST -d @test.json https://ez9pmaodek.execute-api.us-west-2.amazonaws.com/Feature/property --header "Content-Type:application/json"

Content of test.json:
{"property_id": 1, 

"property_type": 1, 
"property_address": "111 Main St", 
"property_city": "Seattle",
"property_state": "WA",
"property_zip": 12345,
"property_country": "USA"};

Expected result:
Status code 400, Error message

Received:
{"statusCode":400,"body":"{\"message\":\"Missing required data\"}"}

**POST json with extra parameter**
C:\>curl -X POST -d @test.json https://ez9pmaodek.execute-api.us-west-2.amazonaws.com/Feature/property --header "Content-Type:application/json"

Content of test.json:
{"property_id": 1, 
"property_name": "foo property", 
"property_foo": "foofooo", 
"property_type": 1, 
"property_address": "111 Main St", 
"property_city": "Seattle",
"property_state": "WA",
"property_zip": 12345,
"property_country": "USA"  };

Expected result:
Status code 400, Error message

Received:
Warning: Couldn't read data from file "test.json", this makes an empty POST.
{"message":"Forbidden"}

**Bug Reports**

**POST json with duplicate parameter**
C:\>curl -X POST -d @test.json https://ez9pmaodek.execute-api.us-west-2.amazonaws.com/Feature/property --header "Content-Type:application/json"

Content of test.json:
{"property_id": 1, 
"property_name": "foo property", 
"property_name": "foo property", 
"property_type": 1, 
"property_address": "111 Main St", 
"property_city": "Seattle",
"property_state": "WA",
"property_zip": 12345,
"property_country": "USA"};

Expected result:
Status code 400, Error message

Received:
{"statusCode":200,"body":"{\"property_id\":1,\"property_name\":\"foo property\",\"property_type\":1,\"property_address\":\"111 Main St\",\"property_city\":\"Seattle\",\"property_state\":\"WA\",\"property_zip\":12345,\"property_country\":\"USA\"}"}

**In .yaml file** 
I would expect to see following response codes: 
 **201 Created** for success rather than 200
**500 Internal Server Error**
