### ISSUE TITLE
Test Creating new users with appropriate group assignment

### ISSUE THREAD

**Issue by mattyplo** [North-Seattle-College/ad440-winter2020-thursday-repo#253]
Test Task #252

**Comment by YunFSui** [comment]
# Objective
Test AWS Cognito user creation and management script by following the **Test Consideration** in [task wiki](https://github.com/North-Seattle-College/ad440-winter2020-thursday-repo/wiki/Cognito-User-Creation-&-Automation).

# Test Method
Run script create_cognito_user.py in AWS CLI enabled environment, verify results use temp email account and Cognito console.

# Test Result
- Create user -n with email -e with/without assigning a group -g :: expected: user created with/without group assignment, email sent to address provided.

    _Create user as expected._

- Attempt to create user that already exists :: expected: error "User account already exists."

    _Error handling as expected, even when username contain capital letters._

- Create and delete users in the same command :: expected: error as these commands are mutually exclusive, "argument -d/--delete: not allowed with argument -n/--new."

    _Behavior as expected_

- Create user with capitol letters :: expected: user is created with all lowercase

    _Behavior as expected_

- Create user -n with/without invalid format email -e :: expected: user is requested to enter a valid email, "Invalid email address format" is produced if 'q' to quit is pressed instead.

    _Behavior as expected_

- Update user -u by adding group -g :: expected: user is added to group

    _Behavior as expected_

- Update user -u by removing group -r :: expected: user is removed from group

    _Behavior as expected_

- Update user -u without adding -g/ removing -r group :: expected: message "No action taken, add -g {groupname} or -r {groupname} at command line."

    _Behavior as expected_

- View list -l :: expected: list of all groups and their precedencies are displayed.

    _Behavior as expected_

- Create user -n by adding invalid -g with valid email -e :: expected: error message and list of valid groups are produced.

    _Command line behavior as expected, a user with on assigned group is created._

- Delete user -d with valid User Pool ID -p :: expected: confirmation message is sent. If 'y' or 'yes' then user deleted, otherwise not.

    _Behavior as expected_

- Create user with invalid User Pool ID -p :: expected: error "User pool {user-pool-id} does not exist." or error for incorrect format.

    _Behavior as expected_

- Delete user -d that doesn't exist :: expected: error "User does not exist."

    _Behavior as expected_

# Other Considerations
It maybe beneficial to also add a list all user feature in the future. But overall, good job!
