### ISSUE TITLE
Travis CI fails to deploy application when new code pushed to feature branch

### ISSUE THREAD

**Issue by kyleo83** [North-Seattle-College/ad440-winter2020-thursday-repo#80]
Steps:
1) Push change to feature-sprint1-michael
2) Travis CI checks will start automatically

Expected: All Travis CI checks pass
Actual: All Travis CI checks fail, application fails to deploy

Excerpt from Job Log:
Logging in with Access Key: ****************y_id
Beginning upload of 32490 files with 5 threads.
Preparing deploy
Deploying application
failed to deploy

**Comment by mattyplo** [comment]
I created a new set of AWS_ACCESS_KEYs.  I set them as environment variables in the Travis-CI web console for our project.  

AWS_ACCESS_KEY2
AWS_SECRET_ACCESS_KEY2

These successfully uploaded the deployment directory into an s3 bucket.  The YAML looks like:
`language: node_js
node_js:
- node
script:
- npm test
- npm run build
deploy:
  skip_cleanup: true
  provider: s3
  access_key_id: "$AWS_ACCESS_KEY2_ID"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY2"
  bucket: feature-sprint2-mattyplo
  acl: bucket_owner_full_control
  region: us-west-2
  local_dir: build
  on:
    repo: North-Seattle-College/ad440-winter2020-thursday-repo
    branch: feature-sprint1-travis-mattyplo
branches:
  only:
  - feature-sprint1-travis-mattyplo`

Everything seemed alright with Michael's original script.  The issue was incorrectly inputting the access key and the secret acces key into the environment variables in Travis-CI.

**Comment by mattyplo** [comment]
I have updated our .travis.yml.  It now pushes and deploys a react application live to the bucket mentioned in the config. 
[feature-sprint2-mattyplo](https://github.com/North-Seattle-College/ad440-winter2020-thursday-repo/tree/feature-sprint2-mattyplo)
